// ─────────────────────────────────────────────────────────────────────────────
//  ROOT DATA ARRAY
//  Add new projects here. Set `highlight: true` for homepage featured picks.
//  category must be one of: 'Full Stack' | 'Frontend' | 'Backend' | 'AI'

// https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=900&q=80 ===== VERY Beautiful backend Image + Server Icon + Sparkles ICON
// desc = max 25-30 words, preview = 4 lines max, preview = max 8 words,

import { Heart, Layers, Server, ShieldCheck, Pizza, Tv, GraduationCap,Calculator, HandHeart, CarFront } from "lucide-react";

// ─────────────────────────────────────────────────────────────────────────────
export const allProjects = [
    {
        id: 'PeerLearn',
        index: '01',
        title: 'PeerLearn',
        subtitle: 'PeerLearn: Peer Tutoring and Academic Support Platform',
        category: 'Full Stack',
        year: '2024',
        highlight: true,
        image: 'https://res.cloudinary.com/do7nin6oo/image/upload/v1780252489/home_hhbagg.png',
        desc: 'A full-stack peer tutoring platform connecting students with tutors through secure authentication, smart matching, session scheduling, course support, real-time communication, and AI-powered academic assistance.',
        tags: ['Next.js', 'Express.js', 'TypeScript', 'PostgreSQL', 'Tailwind CSS', 'Prisma', 'Redux', 'Gemini 2.5F', 'WebSocket', 'JWT'],
        metrics: [
            { label: 'API', value: 'REST' },
            // { label: 'Model', value: 'REST' },
            { label: 'DB Type', value: 'SQL' },
            { label: 'Uptime', value: '99.9%' },
            { label: 'R. Time', value: '256ms' },
        ],
        github: 'https://github.com/PIYAS79/PeerLearn',
        live: 'https://peerlearn-mu.vercel.app',
        accent: '#f97316',
        accentMuted: 'rgba(249,115,22,0.08)',
        Icon: GraduationCap,
        preview: [
            { type: 'cmd', text: '$ npm run peerlearn' },
            { type: 'ok', text: '✔ Find expert tutors and manage requests' },
            { type: 'data', text: '→ Book study sessions and upload resources' },
            { type: 'data', text: '→ Real-time communication through WebSocket' },
            { type: 'info', text: '⬡ AI based academic evaluation ' },
        ],
    },
    {
        id: 'share-a-bite',
        index: '02',
        title: 'Share-A-Bite',
        subtitle: 'Community Food Sharing Platform',
        category: 'Full Stack',
        year: '2024',
        highlight: true,
        image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=900&q=80',
        desc: 'A full-stack food sharing platform that connects donors and recipients in real time, reducing food waste through secure donations, instant requests, location-based matching, and live updates.',
        tags: ['React.js', 'Express.js', 'Redux', 'MongoDB', 'JWT', 'Mongoose', 'Tailwind CSS', 'DaisyUI', 'TypeScript'],
        metrics: [
            { label: 'API', value: 'REST' },
            // { label: 'Model', value: 'REST' },
            { label: 'DB Type', value: 'NoSQL' },
            { label: 'Uptime', value: '98.7%' },
            { label: 'R. Time', value: '312ms' },
        ],
        github: 'https://github.com/PIYAS79/Share_A_Bite_Client_Side',
        live: 'https://share-a-bite-b0bdb.web.app',
        accent: '#f97316',
        accentMuted: 'rgba(249,115,22,0.08)',
        Icon: HandHeart,
        preview: [
            { type: 'cmd', text: '$ npm run share-a-bite' },
            { type: 'ok', text: '✔ Donate surplus food with friends' },
            { type: 'data', text: '→ Find nearby donations for anyone' },
            { type: 'data', text: '→ Track donation status from the dashboard' },
            { type: 'info', text: '⬡ Real-time food sharing and management' },
        ],
    },
    {
        id: 'mov-x',
        index: '03',
        title: 'Mov-X',
        subtitle: 'Cinematic Movie Discovery Engine',
        category: 'Frontend',
        year: '2024',
        highlight: false,
        image: 'https://res.cloudinary.com/do7nin6oo/image/upload/v1780351920/Screenshot_from_2026-06-02_04-11-40_vzpzu7.png',
        desc: 'A modern movie discovery platform featuring lightning-fast search, detailed movie information, genre exploration, trailer viewing, and a cinematic user experience powered by the TMDB API.',
        tags: ['React.js', 'TypeScript', 'Tailwind CSS', 'TMDB API', 'Framer Motion', 'DaisyUI'],
        metrics: [
            { label: 'API', value: 'REST (TMDB)' },
            // { label: 'Model', value: 'REST' },
            // { label: 'DB Type', value: 'NoSQL' },
            { label: 'Uptime', value: '100%' },
            { label: 'R. Time', value: '100ms' },
        ],
        github: 'https://github.com/PIYAS79/movie-app001',
        live: 'https://mov-x001.netlify.app',
        accent: '#f97316',
        accentMuted: 'rgba(249,115,22,0.07)',
        Icon: Tv,
        preview: [
            { type: 'cmd', text: '$ npm run mov-x' },
            { type: 'ok', text: '✔ Search any movie anytime anywhere' },
            { type: 'data', text: '→ Browse movie wiht various genres' },
            { type: 'data', text: '→ Track official trailers and IMDB details' },
            { type: 'info', text: '⬡ Cinematic movie details experience' },
        ],
    },
    {
        id: 'b-marry',
        index: '04',
        title: 'B-Marry',
        subtitle: 'Premium Matrimonial Architecture',
        category: 'Full Stack',
        year: '2025',
        highlight: true,
        image: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=900&q=80',
        desc: 'A full-stack matrimonial platform with verified profiles, smart matchmaking, advanced search filters, secure authentication, privacy controls, and personalized recommendations for meaningful connections.',
        tags: ['React.js', 'Express.js', 'TypeScript', 'MongoDB', 'Mongoose', 'Redux', 'Tailwind CSS', 'JWT', 'Stripe'],
        metrics: [
            { label: 'API', value: 'REST' },
            // { label: 'Model', value: 'REST' },
            { label: 'DB Type', value: 'NoSQL' },
            { label: 'Uptime', value: '99.7%' },
            { label: 'R. Time', value: '374ms' },
        ],
        github: 'https://github.com/PIYAS79/BMarry_Client_Side',
        live: 'https://bmarry.web.app',
        accent: '#f97316',
        accentMuted: 'rgba(249,115,22,0.07)',
        Icon: Heart,
        preview: [
            { type: 'cmd', text: '$ npm run b-marry' },
            { type: 'ok', text: '✔ Create verified profile with confidence' },
            { type: 'data', text: '→ Advanced match filters | premium profile' },
            { type: 'data', text: '→ Secure private messaging and info tracking' },
            { type: 'info', text: '⬡ Smart compatibility matching' },
        ],
    },
    {
        id: 'food-moneky',
        index: '05',
        title: 'Food Monkey',
        subtitle: 'Online Food Ordering and Restaurant tracking App',
        category: 'Full Stack',
        year: '2025',
        highlight: false,
        image: 'https://res.cloudinary.com/do7nin6oo/image/upload/v1780351492/Screenshot_from_2026-06-02_04-04-32_d9vnzo.png',
        desc: 'A full-stack food ordering platform that enables users to browse restaurants, place orders, track deliveries in real time, manage carts, and enjoy a seamless ordering experience.',
        tags: ['React.js', 'Express.js', 'TypeScript', 'MongoDB', 'Mongoose', 'Redux', 'Tailwind CSS', 'JWT', 'Zod'],
        metrics: [
            { label: 'API', value: 'REST' },
            // { label: 'Model', value: 'REST' },
            { label: 'DB Type', value: 'NoSQL' },
            { label: 'Uptime', value: '97.2%' },
            { label: 'R. Time', value: '314ms' },
        ],
        github: 'https://github.com/PIYAS79/FoodMonkey-Client',
        live: 'https://food-monkey-8ea19.web.app',
        accent: '#f97316',
        accentMuted: 'rgba(249,115,22,0.07)',
        Icon: Pizza,
        preview: [
            { type: 'cmd', text: '$ npm run foodmonkey' },
            { type: 'ok', text: '✔ Browse nearby restaurants and order foods' },
            { type: 'data', text: '→ Add items to cart and manage orders' },
            { type: 'data', text: '→ Track orders live' },
            { type: 'info', text: '⬡ Real-time delivery tracking' },
        ],
    },
    {
        id: 'bmb',
        index: '06',
        title: 'BMB',
        subtitle: 'Online Car Showroom and Booking App',
        category: 'Full Stack',
        year: '2024',
        highlight: false,
        image: 'https://cdn.dribbble.com/userupload/27976378/file/original-9805a2b6ee79e693e2246333e0981537.png?resize=1024x728&vertical=center',
        desc: 'A full-stack car showroom platform where users can explore vehicles, view detailed specifications, book test drives, manage purchases, and discover their ideal car seamlessly.',
        tags: ['React.js', 'Express.js', 'MongoDB', 'TypeScript', 'JWT', 'DaisyUI'],
        metrics: [
            { label: 'API', value: 'REST' },
            // { label: 'Model', value: 'REST' },
            { label: 'DB Type', value: 'NoSQL' },
            { label: 'Uptime', value: '98.8%' },
            { label: 'R. Time', value: '414ms' },
        ],
        github: 'https://github.com/PIYAS79/BMB_Car_Shop_Client_Side',
        live: 'https://bmb-brand-web.web.app',
        accent: '#f97316',
        accentMuted: 'rgba(249,115,22,0.07)',
        Icon: CarFront,
        preview: [
            { type: 'cmd', text: '$ npm run bmb' },
            { type: 'ok', text: '✔ Browse available cars by category' },
            { type: 'data', text: '→ View any car details' },
            { type: 'data', text: '→ Book test drives and manage purchases' },
            { type: 'info', text: '⬡ Smart vehicle discovery' },
        ],
    },
    {
        id: 'code-note',
        index: '07',
        title: 'Code Note',
        subtitle: 'University based code snippet sharing platform',
        category: 'Full Stack',
        year: '2025',
        highlight: true,
        image: 'https://res.cloudinary.com/do7nin6oo/image/upload/v1780263781/Screenshot_from_2026-06-01_03-39-56_j8ues5.png',
        desc: 'A university-focused code sharing platform where students can upload, discover, organize, and exchange programming snippets, fostering collaboration, learning, and academic productivity.',
        tags: ['React.js', 'Express.js', 'TypeScript', 'MongoDB', 'Redux', 'Tailwind CSS', 'JWT', 'Nodemailer', 'Zod'],
        metrics: [
            { label: 'API', value: 'REST' },
            // { label: 'Model', value: 'REST' },
            { label: 'DB Type', value: 'NoSQL' },
            { label: 'Uptime', value: '99.8%' },
            { label: 'R. Time', value: '226ms' },
        ],
        github: 'https://github.com/PIYAS79/CODE_NOTE_Client',
        live: 'https://codenote79.netlify.app',
        accent: '#f97316',
        accentMuted: 'rgba(249,115,22,0.07)',
        Icon: Layers,
        preview: [
            { type: 'cmd', text: '$ npm run codenote' },
            { type: 'ok', text: '✔ Share any code snippets with friends' },
            { type: 'data', text: '→ Discover student solutions and request code' },
            { type: 'data', text: '→ Organize coding notes' },
            { type: 'info', text: '⬡ University coding collaboration' },
        ],
    },
    {
        id: 'resistance-measurement',
        index: '08',
        title: 'Resistance Measurement',
        subtitle: 'Resistor color code measurement tool',
        category: 'Frontend',
        year: '2022',
        highlight: false,
        image: 'https://res.cloudinary.com/do7nin6oo/image/upload/v1780264531/Screenshot_from_2026-06-01_03-50-02_sswbap.png',
        desc: 'A resistor color code calculator that helps users identify resistor values, tolerance ranges, and resistance measurements through an intuitive interface designed for electronics learning.',
        tags: ['JavaScript', 'HTML5', 'CSS3'],
        metrics: [
            // { label: 'API', value: 'REST' },
            // { label: 'Model', value: 'REST' },
            // { label: 'DB Type', value: 'NoSQL' },
            { label: 'Uptime', value: '99.9%' },
            { label: 'R. Time', value: '127ms' },
        ],
        github: 'https://github.com/PIYAS79/Resistance-Measurement-with-Color-Colde',
        live: 'https://iridescent-liger-35a0b3.netlify.app',
        accent: '#f97316',
        accentMuted: 'rgba(249,115,22,0.07)',
        Icon: Calculator,
        preview: [
            { type: 'cmd', text: '$ npm run resistance-tool' },
            { type: 'ok', text: '✔ Select resistor bands' },
            { type: 'data', text: '→ Calculate resistance value' },
            { type: 'data', text: '→ View tolerance range' },
            { type: 'info', text: '⬡ Instant color code decoding' },
        ],
    },
];